Byzhynar integration branch
LuxoftAKutsan/sdl_core pull request #112
Opened 2017-05-31 13:40 UTC by AByzhynar

This PR provides the following changes:

Main CMakeLists.txt and MD files' changes
- Added necessary flags, variables adn their handling to make possible to
  build SDL with RC functionality
- Updated COMMITERS.md with actual information

Config Profile's changes:  
- Updated config profle to support plugin folder

Connection hamdler's changes:
- Updated connection handler OnDeviceRemove() method

Formatters' & Smart Objects' changes: 
 - Removed redundant and commented code from formatters & smart objects unit tests 

Security Manager's changes: 
 - Added mandatory header files includes to SSL context
 - Added funcion GetName to get certificate name and some logging to SSL
    context
 - Added function SetCertExpTime and updated appropriate mock classes
    
Media manager's changes: 
 - Updated header guards
 - Included necessary paths, added libriries and added
    RC fuctionality support to CMakeLists
 - Added REMOTE_CONTROL handling to CmakeLists
 - Replaced raw ptrs with SharedPtr in setters for unit tests
 - Added/updated unit tests for media manager

Utils' changes: 
  - Added explicit header <fstream>
  - Removed unused preprocessor directives handling of __QNXNTO__
  - Added export function definition
  - Added case sensitive comparison methods
  - Update UT macro FRIEND_TEST
  - Added timer_thread class
  - Fixed memory leaks
  - Updated utils unit tests

Telemetry Monitor's changes:
  - Added TimeTester library creation and included RC functionality
    directories
  - Fixed memory leaks
 
Protocol handler's changes:
  - Added service type check and named parameter protocol_version
  
Transpport Manager
  - Enabled previously disabled nit test
  
Updated auxiliary tools

2017-05-31 13:41 UTC, AByzhynar commented
@LuxoftAKutsan @anosach-luxoft @dev-gh @AKalinich-Luxoft Please review

2017-05-31 14:29 UTC, LuxoftAKutsan requested changes

2017-05-31 14:29 UTC, LuxoftAKutsan commented on CMakeLists.txt
> +if (DEBUG_OPTION)
@AByzhynar this changes are redundant

2017-05-31 14:29 UTC, LuxoftAKutsan commented on CONTRIBUTING.md
> +In order to accept Pull Requests from contributors, you must first sign [the Contributor's License Agreement](https://docs.google.com/forms/d/1VNR8EUd5b46cQ7uNbCq1fJmnu0askNpUp5dudLKRGpU/viewform). I
@AByzhynar please remove changes.

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/config_profile/include/config_profile/profile.h
> +  const uint16_t audio_streaming_port() const OVERRIDE;
@AByzhynar description missed

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/config_profile/include/config_profile/profile.h
>    uint32_t transport_manager_disconnect_timeout() const OVERRIDE;
@AByzhynar wrong description

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/config_profile/src/profile.cc
> +  logs_enabled_ = true;
@AByzhynar please remove this line.

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/config_profile/test/profile_test.cc
> +}  // namespace profile_test
@AByzhynar please check check if actual name of namespace is profile_test

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/include/security_manager/crypto_manager.h
> +  virtual void SetCertExpTime(const std::string& time) = 0;
@AByzhynar  please check if this method used

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/include/utils/timer_thread.h
> +/*
@AByzhynar please check if htis file used

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/media_manager/CMakeLists.txt
> +find_package(Gstreamer-1.0 REQUIRED)
@AByzhynar I am nut sure that is required changes. Please remove it.

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/media_manager/CMakeLists.txt
> +    ${COMPONENTS_DIR}/can_cooperation/include/
@AByzhynar this changes required

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/media_manager/test/media_manager_impl_test.cc
> +  const std::string record_file_path =
@AByzhynar please remove changes related to extended media mode

2017-05-31 14:29 UTC, LuxoftAKutsan commented on src/components/security_manager/src/ssl_context_impl.cc
> +    LOG4CXX_DEBUG(logger_,
@AByzhynar are you sure, that this code should be deleted

2017-05-31 15:12 UTC, AByzhynar commented on src/components/config_profile/test/profile_test.cc
> +}  // namespace profile_test
@LuxoftAKutsan It is actual. Checked.

2017-05-31 15:25 UTC, AByzhynar commented on src/components/include/security_manager/crypto_manager.h
> +  virtual void SetCertExpTime(const std::string& time) = 0;
@LuxoftAKutsan It was added by this PR: https://github.com/smartdevicelink/sdl_core/pull/1434
Do you suggest - I have to remove all changes provided by this PR?

2017-05-31 15:28 UTC, AByzhynar commented on src/components/security_manager/src/ssl_context_impl.cc
> +    LOG4CXX_DEBUG(logger_,
@LuxoftAKutsan If I understand correctly this code was not removed but just extracted to separate function and used here.

2017-06-01 06:34 UTC, AKalinich-Luxoft approved these changes

2017-06-01 06:56 UTC, dev-gh commented on src/components/CMakeLists.txt
> +    add_subdirectory(./telemetry_monitor)
@AByzhynar 
I think formatting should be fixed

2017-06-01 06:56 UTC, dev-gh commented on CMakeLists.txt
> +if (ENABLE_GCOV)
@AByzhynar 
Not related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/application_manager/test/commands/mobile/show_test.cc
> +  EXPECT_CALL(mock_message_helper_,
@AByzhynar 
Don't think its related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/connection_handler/src/connection_handler_impl.cc
>  }
@AByzhynar 
Don't think its related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/include/test/media_manager/mock_media_manager.h
> +#ifndef SRC_COMPONENTS_INCLUDE_TEST_MEDIA_MANAGER_MOCK_MEDIA_MANAGER_H_
@AByzhynar 
Don't think its related to RC as well as other media related changes

2017-06-01 06:56 UTC, dev-gh commented on src/components/include/utils/custom_string.h
> +   * @brief Compares the value of the string (case sensitive).
@AByzhynar 
Don't think its related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/security_manager/src/ssl_context_impl.cc
> +std::string GetName(X509_NAME* x509_name) {
@AByzhynar 
Don't think its related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/telemetry_monitor/CMakeLists.txt
> +set (LIBRARIES
@AByzhynar 
Don't think its related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/utils/src/file_system.cc
> -#ifdef __QNXNTO__
@AByzhynar 
Don't think its related to RC

2017-06-01 06:56 UTC, dev-gh commented on src/components/formatters/test/meta_formatter_test.cc
> -  // Uncomment code to print objects in console
@AByzhynar 
I think task was to take only RC changes but this does not have to do with these changes

2017-06-01 09:25 UTC, AByzhynar commented on src/components/utils/src/file_system.cc
> -#ifdef __QNXNTO__
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:25 UTC, AByzhynar commented on src/components/telemetry_monitor/CMakeLists.txt
> +set (LIBRARIES
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:26 UTC, AByzhynar commented on src/components/security_manager/src/ssl_context_impl.cc
> +std::string GetName(X509_NAME* x509_name) {
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:26 UTC, AByzhynar commented on src/components/include/utils/custom_string.h
> +   * @brief Compares the value of the string (case sensitive).
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:27 UTC, AByzhynar commented on src/components/include/test/media_manager/mock_media_manager.h
> +#ifndef SRC_COMPONENTS_INCLUDE_TEST_MEDIA_MANAGER_MOCK_MEDIA_MANAGER_H_
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:28 UTC, AByzhynar commented on src/components/formatters/test/meta_formatter_test.cc
> -  // Uncomment code to print objects in console
@dev-gh No. The task is to cmbine RC changes with develop and with CRQs

2017-06-01 09:28 UTC, AByzhynar commented on src/components/connection_handler/src/connection_handler_impl.cc
>  }
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:28 UTC, AByzhynar commented on src/components/application_manager/test/commands/mobile/show_test.cc
> +  EXPECT_CALL(mock_message_helper_,
@dev-gh Right but these changes are critical and needed for further development.

2017-06-01 09:41 UTC, AByzhynar commented on src/components/CMakeLists.txt
> +    add_subdirectory(./telemetry_monitor)
@dev-gh Will be changed back

2017-06-01 09:44 UTC, dev-gh approved these changes

2017-06-01 12:36 UTC, AByzhynar commented
@LuxoftAKutsan All changes done. Commits amended. Please check.

2017-06-01 12:41 UTC, LuxoftAKutsan approved these changes

2017-06-01 12:41 UTC, merged