Move RC functionality for LifeCycle, HmiMessageHandler and API's
LuxoftAKutsan/sdl_core pull request #113
Opened 2017-05-31 14:54 UTC by AKalinich-Luxoft

Moved RC functionality for LifeCycle, HmiMessageHandler and API's.
- `CMakeLists.txt`: added new include_directories, preloaded pt json for RC
- `hmi_capabilities.json`: reordered property
- `life_cycle.h`: added RC conditional includes
- `sdl_preloaded_pt.json`: removed WayPoints RPCs
- `smartDeviceLink.ini`: added RC settings
- `hmi_message_adapter_impl` & `hmi_message_handler_impl`: added virtual function `SubscribeToHMINotification` for RC needs
- `messagebroker_adapter.cc`: reordered RPC subscriptions, added RC notifications subscription
- `hmi_message_handler_impl_test.cc`: fixed return result in some UT
- `HMI_API.xml`: added RC interface and related functions, fixed identations
- `MOBILE_API.xml`: added RC-related structs, updated version, fixed identations

**Note**
API files changes recommended to view [without whitespaces](https://github.com/AKalinich-Luxoft/sdl_core/commit/5ef6e4683f14647b5d324c91fae5d67efba055b1?w=1)

2017-05-31 14:56 UTC, AKalinich-Luxoft commented
@AByzhynar, @dev-gh, @LuxoftAKutsan, @anosach-luxoft please review

2017-06-01 06:47 UTC, LuxoftAKutsan requested changes

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/appMain/CMakeLists.txt
> +  ${CMAKE_SOURCE_DIR}/src/3rd_party/dbus-1.7.8
@AKalinich-Luxoft dbus is redundant there

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/appMain/CMakeLists.txt
> +if( NOT CMAKE_BUILD_TYPE )
@AKalinich-Luxoft  this code looks like also redundant. Probably this code is already available in main CMaleLists.txt

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/appMain/hmi_capabilities.json
> +        "keyboardPropertiesDefault":
@AKalinich-Luxoft this changes are not related to Rev

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/appMain/sdl_preloaded_pt.json
> -            "WayPoints": {
@AKalinich-Luxoft this changes not related to Rev

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/hmi_message_handler/src/messagebroker_adapter.cc
> +  MessageBrokerController::subscribeTo("BasicCommunication.OnAppActivated");
@AKalinich-Luxoft there to many changes for reverse. Please find out this additional subscribes are required and remove others changes

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/HMI_API.xml
> +  <element name="audiPassThruIcon">
@AKalinich-Luxoft this changes not related to RC

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/HMI_API.xml
> +<enum name="SteeringWheelLocation">
@AKalinich-Luxoft this cnahges not related to RC

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +<interface name="Ford Sync RAPI" version="4.4" date="2017-04-27">
@AKalinich-Luxoft there should be 4.4.0

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> -  <function name="SubscribeWayPoints" functionID="SubscribeWayPointsID" messagetype="request">
@AKalinich-Luxoft I suppose this should not be deleted

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> -  <function name="OnWayPointChange" functionID="OnWayPointChangeID" messagetype="notification">
@AKalinich-Luxoft this function should not be deleted

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +      Callback including encoded data of any SyncP packets that SYNC needs to send back to the mobile device.
@AKalinich-Luxoft please avoid fixing formating. It is not clear what changes actually done

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +  <function name="SubscribeWayPoints" functionID="SubscribeWayPointsID" messagetype="request">
@AKalinich-Luxoft not related to RC

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +  <function name="SubscribeWayPoints" functionID="SubscribeWayPointsID" messagetype="response">
@AKalinich-Luxoft not related to RC

2017-06-01 06:47 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +  <function name="SetAudioStreamingIndicator" functionID="SetAudioStreamingIndicatorID" messagetype="request">
@AKalinich-Luxoft not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/appMain/CMakeLists.txt
> +  ${SecurityManagerIncludeDir}
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/appMain/CMakeLists.txt
> +  ${ENCRYPTION_INCLUDE_DIRECTORY}
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/appMain/CMakeLists.txt
> +    hmi_capabilities.json
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/components/hmi_message_handler/include/hmi_message_handler/hmi_message_handler_impl.h
> +  mutable sync_primitives::Lock observer_locker_;
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/components/hmi_message_handler/src/hmi_message_handler_impl.cc
> +  message_adapters_.clear();
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/components/hmi_message_handler/src/hmi_message_handler_impl.cc
> +  sync_primitives::AutoLock lock(message_adapters_locker_);
@AKalinich-Luxoft 
Seems is not related to RC and same changes below

2017-06-01 07:05 UTC, dev-gh commented on src/components/hmi_message_handler/src/messagebroker_adapter.cc
> +  MessageBrokerController::subscribeTo("BasicCommunication.OnAppActivated");
@AKalinich-Luxoft 
I believe we have to add changes for RC.* subscriptions only

2017-06-01 07:05 UTC, dev-gh commented on src/components/hmi_message_handler/test/hmi_message_adapter_test.cc
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/components/interfaces/HMI_API.xml
> -<enum name="SteeringWheelLocation">
@AKalinich-Luxoft 
Seems is not related to RC

2017-06-01 07:05 UTC, dev-gh commented on src/components/interfaces/MOBILE_API.xml
>  <?xml version="1.0" standalone="no"?>
@AKalinich-Luxoft 
There are a lot of changes due to formatting which hides real changes so I think that needs to be fixed

2017-06-01 08:40 UTC, AKalinich-Luxoft commented on src/appMain/CMakeLists.txt
> +  ${CMAKE_SOURCE_DIR}/src/3rd_party/dbus-1.7.8
@LuxoftAKutsan removed in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/69b0106c66b759cb7e1c5b56cd36e7c35b1a4867

2017-06-01 08:43 UTC, AKalinich-Luxoft commented on src/appMain/CMakeLists.txt
> +if( NOT CMAKE_BUILD_TYPE )
@LuxoftAKutsan yes, it already exists in main CMaleLists.txt, removed in https://github.com/LuxoftAKutsan/sdl_core/commit/69b0106c66b759cb7e1c5b56cd36e7c35b1a4867

2017-06-01 08:46 UTC, AKalinich-Luxoft commented on src/appMain/hmi_capabilities.json
> +        "keyboardPropertiesDefault":
@LuxoftAKutsan removed from commit due to no more changes in this file

2017-06-01 08:46 UTC, AKalinich-Luxoft commented on src/appMain/sdl_preloaded_pt.json
> -            "WayPoints": {
@LuxoftAKutsan removed from commit due to no more changes in this file

2017-06-01 08:48 UTC, AKalinich-Luxoft commented on src/components/hmi_message_handler/src/messagebroker_adapter.cc
> +  MessageBrokerController::subscribeTo("BasicCommunication.OnAppActivated");
@LuxoftAKutsan there was just subscription reordering. Anyway I just added new RC-related subscriptions. See https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/1be4f2b22b538d88b968d4358a69cada7af38911

2017-06-01 08:48 UTC, AKalinich-Luxoft commented on src/components/interfaces/HMI_API.xml
> +  <element name="audiPassThruIcon">
@LuxoftAKutsan done in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215

2017-06-01 08:48 UTC, AKalinich-Luxoft commented on src/components/interfaces/HMI_API.xml
> +<enum name="SteeringWheelLocation">
@LuxoftAKutsan done in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215

2017-06-01 08:49 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> +<interface name="Ford Sync RAPI" version="4.4" date="2017-04-27">
@LuxoftAKutsan done in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215

2017-06-01 08:49 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> -  <function name="SubscribeWayPoints" functionID="SubscribeWayPointsID" messagetype="request">
@LuxoftAKutsan reverted in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215

2017-06-01 08:49 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> -  <function name="OnWayPointChange" functionID="OnWayPointChangeID" messagetype="notification">
@LuxoftAKutsan reverted in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215

2017-06-01 08:51 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> +      Callback including encoded data of any SyncP packets that SYNC needs to send back to the mobile device.
@LuxoftAKutsan formatting should be done in this file. You could view actual changes using ignore whitespace flag. See this commit using this link https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215?w=1

2017-06-01 08:51 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> +  <function name="SubscribeWayPoints" functionID="SubscribeWayPointsID" messagetype="request">
@LuxoftAKutsan reveted in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215?w=1

2017-06-01 08:51 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> +  <function name="SubscribeWayPoints" functionID="SubscribeWayPointsID" messagetype="response">
@LuxoftAKutsan reverted in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215?w=1

2017-06-01 08:52 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
> +  <function name="SetAudioStreamingIndicator" functionID="SetAudioStreamingIndicatorID" messagetype="request">
@LuxoftAKutsan reverted in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215?w=1

2017-06-01 08:52 UTC, AKalinich-Luxoft commented on src/appMain/CMakeLists.txt
> +  ${SecurityManagerIncludeDir}
@dev-gh removed in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/69b0106c66b759cb7e1c5b56cd36e7c35b1a4867

2017-06-01 08:52 UTC, AKalinich-Luxoft commented on src/appMain/CMakeLists.txt
> +  ${ENCRYPTION_INCLUDE_DIRECTORY}
@dev-gh removed in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/69b0106c66b759cb7e1c5b56cd36e7c35b1a4867

2017-06-01 08:53 UTC, AKalinich-Luxoft commented on src/appMain/CMakeLists.txt
> +    hmi_capabilities.json
@dev-gh it is related because sdl_preloaded_pt.json is installed later in next block of code with RC check.

2017-06-01 08:55 UTC, AKalinich-Luxoft commented on src/components/hmi_message_handler/include/hmi_message_handler/hmi_message_handler_impl.h
> +  mutable sync_primitives::Lock observer_locker_;
@dev-gh this `observer_locker_` lock already was here before provided changes

2017-06-01 08:56 UTC, AKalinich-Luxoft commented on src/components/hmi_message_handler/src/hmi_message_handler_impl.cc
> +  message_adapters_.clear();
@dev-gh removed in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/1be4f2b22b538d88b968d4358a69cada7af38911

2017-06-01 08:59 UTC, AKalinich-Luxoft commented on src/components/hmi_message_handler/src/hmi_message_handler_impl.cc
> +  sync_primitives::AutoLock lock(message_adapters_locker_);
@dev-gh this lock is used in `HMIMessageHandlerImpl::SubscribeToHMINotification` which is RC-related. Also this lock was added in terms of [this PR](https://github.com/smartdevicelink/sdl_core/pull/1245) to fix segfault in related UT.

2017-06-01 09:00 UTC, AKalinich-Luxoft commented on src/components/hmi_message_handler/src/messagebroker_adapter.cc
> +  MessageBrokerController::subscribeTo("BasicCommunication.OnAppActivated");
@dev-gh added only RC-related subscriptions in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/1be4f2b22b538d88b968d4358a69cada7af38911

2017-06-01 09:02 UTC, AKalinich-Luxoft commented on src/components/hmi_message_handler/test/hmi_message_adapter_test.cc
@dev-gh related indirectly due to changes in `mock_hmi_message_handler_settings.h` in #112

2017-06-01 09:03 UTC, AKalinich-Luxoft commented on src/components/interfaces/HMI_API.xml
> -<enum name="SteeringWheelLocation">
@dev-gh fixed in https://github.com/LuxoftAKutsan/sdl_core/pull/113/commits/ab9adc7c6996e68e910941d6e3ed04f751e49215?w=1

2017-06-01 09:03 UTC, AKalinich-Luxoft commented on src/components/interfaces/MOBILE_API.xml
>  <?xml version="1.0" standalone="no"?>
@dev-gh formatting should be done in this file. You could view actual changes using ignore whitespace flag. See this commit using this link ab9adc7?w=1

2017-06-01 09:26 UTC, dev-gh approved these changes

2017-06-01 11:44 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +      Callback including encoded data of any SyncP packets that SYNC needs to send back to the mobile device.
@AKalinich-Luxoft Ok, greate!

2017-06-01 11:45 UTC, LuxoftAKutsan approved these changes

2017-06-01 11:45 UTC, merged