Adds CAN cooperation part of RC implementation
LuxoftAKutsan/sdl_core pull request #118
Opened 2017-07-03 14:58 UTC by dev-gh

Adds CAN cooperation part of RC implementation  w/o RPC implemenation and w/o zone concept

2017-07-03 14:59 UTC, dev-gh commented
@AKalinich-Luxoft @LuxoftAKutsan @LitvinenkoIra @AByzhynar Please review

2017-07-04 08:55 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/InteriorVehicleDataCapabilities.json
> +      {"moduleType": "CLIMATE"}
@dev-gh what a strange duplicates here?

2017-07-04 11:12 UTC, dev-gh commented on src/components/can_cooperation/InteriorVehicleDataCapabilities.json
> +      {"moduleType": "CLIMATE"}
@AKalinich-Luxoft 
Previously there were different zones. Fixed with ba3bb8f.

2017-07-04 11:43 UTC, LuxoftAKutsan requested changes

2017-07-04 11:43 UTC, LuxoftAKutsan commented on src/components/can_cooperation/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-fPIC -std=gnu++0x -Wall -Wno-deprecated-declarations -Werror ${GCOV_FLAGS}")
@dev-gh this cmake is not place for such logic ( it should be in main cmake)

2017-07-04 11:43 UTC, LuxoftAKutsan commented on src/components/can_cooperation/CMakeLists.txt
> +    ${CAN_SOURCE_DIR}/can_module.cc
@dev-gh lets try to use batch sources collecting

2017-07-04 11:59 UTC, dev-gh commented on src/components/can_cooperation/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-fPIC -std=gnu++0x -Wall -Wno-deprecated-declarations -Werror ${GCOV_FLAGS}")
@LuxoftAKutsan 
Done with 7ada254

2017-07-04 11:59 UTC, dev-gh commented on src/components/can_cooperation/CMakeLists.txt
> +    ${CAN_SOURCE_DIR}/can_module.cc
@LuxoftAKutsan 
Done with 7ada254

2017-07-04 12:35 UTC, AKalinich-Luxoft approved these changes

2017-07-04 12:40 UTC, merged