GetInteriorVehicleDataCapabilities API of Reverse SDL
LuxoftAKutsan/sdl_core pull request #127
Opened 2017-07-06 15:06 UTC by dev-gh

Changes contain 
- working build or RSDL 
- basic implementation of GetInteriorVehicleDataCapabilities RPC
- some RPCs have been disabled according to customer proposal (https://github.com/yang1070/sdl_evolution/blob/170b85f894fc64f763b6c600708ff5683004ac89/proposals/NNNN-remote-control-baseline.md)
- code style changes with clang

2017-07-06 15:17 UTC, AByzhynar requested changes

2017-07-06 15:17 UTC, AByzhynar commented on src/components/can_cooperation/include/can_cooperation/commands/get_interior_vehicle_data_capabilities_request.h
> +  void CreateCapabilities(const Json::Value& zone_capabilities,
@dev-gh `zone_capabilities`? Are you sure that we have to handle this parameter?

2017-07-06 15:25 UTC, AByzhynar requested changes

2017-07-06 15:25 UTC, AByzhynar commented on src/components/can_cooperation/src/commands/get_interior_vehicle_data_capabilities_request.cc
> +  Json::Value zone_capabilities;
@dev-gh The same question as above: `Zone_capabilities`? Do we need it?

2017-07-06 15:35 UTC, AKalinich-Luxoft approved these changes

2017-07-06 15:45 UTC, AByzhynar requested changes

2017-07-06 15:45 UTC, AByzhynar commented on src/components/can_cooperation/src/validators/get_interior_vehicle_data_capabilities_response_validator.cc
> +}  // namespace can_cooperation
@dev-gh Please add one empty line at the end of all files

2017-07-07 08:16 UTC, dev-gh commented
@LuxoftAKutsan @LitvinenkoIra 
Please review

2017-07-07 09:02 UTC, dev-gh commented on src/components/can_cooperation/include/can_cooperation/commands/get_interior_vehicle_data_capabilities_request.h
> +  void CreateCapabilities(const Json::Value& zone_capabilities,
@AByzhynar 
Currently there is no clarification from customer on format expected for fallback capabilities, so I would leave these parts untill further information will be provided and than change that accordingly.

2017-07-07 09:03 UTC, dev-gh commented on src/components/can_cooperation/src/commands/get_interior_vehicle_data_capabilities_request.cc
> +  Json::Value zone_capabilities;
@AByzhynar 
Currently there is no clarification from customer on format expected for fallback capabilities, so I would leave these parts untill further information will be provided and than change that accordingly.

2017-07-07 09:09 UTC, dev-gh commented on src/components/can_cooperation/src/validators/get_interior_vehicle_data_capabilities_response_validator.cc
> +}  // namespace can_cooperation
@AByzhynar 
Done with 40ce3c6

2017-07-07 09:43 UTC, LitvinenkoIra approved these changes

2017-07-07 13:20 UTC, AByzhynar approved these changes

2017-07-10 06:53 UTC, LuxoftAKutsan reviewed
@dev-gh changes rebased and cherry picked

2017-07-10 06:53 UTC, LuxoftAKutsan commented on src/components/application_manager/include/application_manager/message.h
> +  //--------------------------------------------------------------------------.
@dev-gh that does this changes mean?

2017-07-10 06:53 UTC, LuxoftAKutsan commented on src/components/application_manager/test/include/application_manager/mock_application.h
> +  MOCK_METHOD1(
@dev-gh please avoid style check in your PR

2017-07-10 06:53 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/can_module.cc
> +    // Disabled
@dev-gh please make it as TODO with description why it is disabled

2017-07-10 11:47 UTC, closed without merging