Fix OnTimeout event handling for CAN module
LuxoftAKutsan/sdl_core pull request #134
Opened 2017-07-11 11:52 UTC by AKalinich-Luxoft

The problem is that `TimerDirector`'s timer checks for every request timeout every 10 seconds and not depends on time when request was sent. For example `TimeDirector` timer check all request for timeouts on 10, 20, 30 second. But if request was sent on 12th second, then default timeout for it will be on 22th second. However this timer will detect timeout and send response only on 30 second.
Also `OnTimeout` event provides wrong result code `TIMED_OUT` instead of `GENERIC_ERROR`.

In this pull request:
- Added more logs to see request controller actions
- Fixed result code for timeout event according to requirements
- Added `GetSecondsToNearestTimeout()` function to return time to the nearest request timeout or default timeout if no requests in queue. This is a correct time to wait before checking timeout. Also this function checks for custom RPC timeouts if present.
- Added `ResetTimer()` function to recalculate timers awaiting time after new request was added to queue

2017-07-11 14:33 UTC, LuxoftAKutsan approved these changes

2017-07-12 06:52 UTC, AByzhynar requested changes

2017-07-12 06:52 UTC, AByzhynar commented on src/components/can_cooperation/src/can_module.cc
> +  LOG4CXX_DEBUG(logger_, "Response to mobile: " << msg->json_message());
@AKalinich-Luxoft How can we differentiate normal response to mobile and this one? Propose to change log message.

2017-07-12 06:52 UTC, AByzhynar commented on src/components/interfaces/HMI_API.xml
> -    <element name="READ_ONLY " value="26"/>
@AKalinich-Luxoft How is this file related to timeouts?

2017-07-12 06:53 UTC, AByzhynar commented on src/components/can_cooperation/src/commands/base_command_request.cc
> +  const bool is_timeout = 0 == strcmp(result_code, result_codes::kTimedOut);
@AKalinich-Luxoft I suggest to add round brackets to improve readability

2017-07-12 06:56 UTC, AByzhynar requested changes

2017-07-12 06:56 UTC, AByzhynar commented on src/components/can_cooperation/src/request_controller.cc
> +      "Timeout for request with correlation_id: " << expired.correlation_id());
@AKalinich-Luxoft Timeout for request xxx - WHAT?

2017-07-12 07:48 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/can_module.cc
> +  LOG4CXX_DEBUG(logger_, "Response to mobile: " << msg->json_message());
@AByzhynar message updated in a522a1615baee23218f4a937b24d9459c680d605

2017-07-12 07:48 UTC, AKalinich-Luxoft commented on src/components/interfaces/HMI_API.xml
> -    <element name="READ_ONLY " value="26"/>
@AByzhynar this changes from another pull request. Rebased.

2017-07-12 07:49 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/commands/base_command_request.cc
> +  const bool is_timeout = 0 == strcmp(result_code, result_codes::kTimedOut);
@AByzhynar done in 6e49a4fed5df88d1b2f288205ec45ca9c131170d

2017-07-12 07:49 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/request_controller.cc
> +      "Timeout for request with correlation_id: " << expired.correlation_id());
@AByzhynar fixed in a522a1615baee23218f4a937b24d9459c680d605

2017-07-12 08:21 UTC, AByzhynar approved these changes

2017-07-12 09:24 UTC, merged