Remove redundant code related to can connection
LuxoftAKutsan/sdl_core pull request #153
Opened 2017-07-17 12:30 UTC by LuxoftAKutsan

Delete all code related to can connection
Delete all validators due to Validation Throw API schema

2017-07-17 12:37 UTC, LitvinenkoIra approved these changes

2017-07-17 14:19 UTC, AByzhynar commented on src/components/can_cooperation/src/can_module.cc
> +  std::string function_name = ExtractFunctionAndAddMetadata(value, *msg);
@LuxoftAKutsan Const?

2017-07-17 14:21 UTC, AByzhynar requested changes

2017-07-17 14:21 UTC, AByzhynar commented on src/components/functional_module/src/plugin_manager.cc
> +    std::string msg_method = ExtractMethodName(value);
@LuxoftAKutsan Const?

2017-07-17 14:56 UTC, AKalinich-Luxoft requested changes

2017-07-17 14:56 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/can_module.cc
> +    std::string function_name = value.get(json_keys::kMethod, "").asCString();
@LuxoftAKutsan const

2017-07-17 14:56 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/can_module.cc
> +    std::string function_name = result.get(json_keys::kMethod, "").asCString();
@LuxoftAKutsan const

2017-07-17 14:56 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/can_module.cc
> +    std::string function_name = error.get(json_keys::kMethod, "").asCString();
@LuxoftAKutsan const

2017-07-18 06:46 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/can_module.cc
> +    std::string function_name = error.get(json_keys::kMethod, "").asCString();
@AKalinich-Luxoft e6d44a9

2017-07-18 06:46 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/can_module.cc
> +    std::string function_name = result.get(json_keys::kMethod, "").asCString();
@AKalinich-Luxoft e6d44a9

2017-07-18 06:46 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/can_module.cc
> +    std::string function_name = value.get(json_keys::kMethod, "").asCString();
@AKalinich-Luxoft e6d44a9

2017-07-18 06:46 UTC, LuxoftAKutsan commented on src/components/functional_module/src/plugin_manager.cc
> +    std::string msg_method = ExtractMethodName(value);
@AByzhynar  e6d44a9

2017-07-18 06:46 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/can_module.cc
> +  std::string function_name = ExtractFunctionAndAddMetadata(value, *msg);
@AByzhynar  e6d44a9

2017-07-18 06:48 UTC, AKalinich-Luxoft approved these changes

2017-07-18 08:59 UTC, AByzhynar requested changes

2017-07-18 08:59 UTC, AByzhynar commented on src/components/can_cooperation/src/can_module.cc
> +      bool is_valid = service()->ValidateMessageBySchema(*msg);
@LuxoftAKutsan Const?

2017-07-18 14:02 UTC, merged