Remove GetInteriorVehicleDataCapabilities
LuxoftAKutsan/sdl_core pull request #154
Opened 2017-07-17 14:43 UTC by LitvinenkoIra

Remove GetInteriorVehicleDataCapabilities, because this RPC is not actual

2017-07-17 14:59 UTC, AKalinich-Luxoft approved these changes

2017-07-18 11:00 UTC, LuxoftAKutsan requested changes

2017-07-18 11:00 UTC, LuxoftAKutsan commented on src/components/interfaces/HMI_API.xml
> -   <param name="interiorVehicleDataCapabilities" type="Common.RemoteControlCapabilities">
@LitvinenkoIra please search for RemoteControlCapabilities

2017-07-18 11:00 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> -    <param name="interiorVehicleDataCapabilities" type="RemoteControlCapabilities">
@LitvinenkoIra please search for RemoteControlCapabilities

2017-07-18 11:03 UTC, AByzhynar approved these changes

2017-07-18 11:32 UTC, LitvinenkoIra commented on src/components/interfaces/HMI_API.xml
> -   <param name="interiorVehicleDataCapabilities" type="Common.RemoteControlCapabilities">
@LuxoftAKutsan deleted this structure

2017-07-18 11:44 UTC, OlesiaV approved these changes

2017-07-18 11:52 UTC, LuxoftAKutsan approved these changes

2017-07-18 11:52 UTC, merged