Feature/ButtonPress
LuxoftAKutsan/sdl_core pull request #157
Opened 2017-07-19 14:23 UTC by LitvinenkoIra

Implemented ButtonPress request base functionality

2017-07-19 14:55 UTC, AKalinich-Luxoft requested changes

2017-07-19 14:55 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +    LOG4CXX_WARN(logger_, "Request module type & data mismatch!");
@LitvinenkoIra better to say "Requested module type and data mismatch" here and in `SendResponse`

2017-07-19 14:55 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +                                  (button_name == enums_value::kLowerVent);
@LitvinenkoIra propose to move this comparison snake to a separate class function and then just use
`const bool module_type_and_button_name = SomeFunctionToCheckButtonName();`

2017-07-19 14:55 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/include/can_cooperation/commands/button_press_request.h
> +  virtual std::string ModuleType(const Json::Value& message) FINAL;
@LitvinenkoIra `virtual` is redundant here

2017-07-19 14:55 UTC, AKalinich-Luxoft commented on src/components/interfaces/HMI_API.xml
> +<function name="ButtonPress" functionID="ButtonPressID" messagetype="request">
@LitvinenkoIra please compare `ButtonPress` function you are adding with it latest version in [mobile](https://github.com/yang1070/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml) and [hmi](https://github.com/yang1070/sdl_core/blob/master/src/components/interfaces/HMI_API.xml) apis.
For example here in request should be also `appID` parameter and response should be without params at all...

2017-07-19 14:59 UTC, LuxoftAKutsan requested changes

2017-07-19 14:59 UTC, LuxoftAKutsan commented on src/components/can_cooperation/include/can_cooperation/commands/button_press_request.h
> +  virtual std::string ModuleType(const Json::Value& message) FINAL;
@LitvinenkoIra remove virtual

2017-07-19 14:59 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/commands/button_press_request.cc
> + Copyright (c) 2013, Ford Motor Company
@LitvinenkoIra 2017

2017-07-19 14:59 UTC, LuxoftAKutsan commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +  bool module_type_and_button_name = true;
@LitvinenkoIra button_name_matches_module_type

2017-07-19 14:59 UTC, LuxoftAKutsan commented on src/components/interfaces/MOBILE_API.xml
> +
@LitvinenkoIra empty line redundant

2017-07-19 14:59 UTC, LuxoftAKutsan commented on src/components/interfaces/HMI_API.xml
> +<function name="ButtonPress" functionID="ButtonPressID" messagetype="response">
@LitvinenkoIra add @OlesiaV  to review

2017-07-19 16:54 UTC, AByzhynar requested changes

2017-07-19 16:54 UTC, AByzhynar commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +  const bool validate_result = application_manager::SUCCESS ==
@LitvinenkoIra Can not see further usage of this variable...

2017-07-20 09:17 UTC, OlesiaV approved these changes

2017-07-20 10:56 UTC, LitvinenkoIra commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +                                  (button_name == enums_value::kLowerVent);
@AKalinich-Luxoft Done
9402dc90b74d4c3d4932b95768ab1514f813f50d

2017-07-20 10:56 UTC, LitvinenkoIra commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +    LOG4CXX_WARN(logger_, "Request module type & data mismatch!");
@AKalinich-Luxoft Done
9402dc90b74d4c3d4932b95768ab1514f813f50d

2017-07-20 10:56 UTC, LitvinenkoIra commented on src/components/can_cooperation/include/can_cooperation/commands/button_press_request.h
> +  virtual std::string ModuleType(const Json::Value& message) FINAL;
@AKalinich-Luxoft Done
9402dc90b74d4c3d4932b95768ab1514f813f50d

2017-07-20 10:56 UTC, LitvinenkoIra commented on src/components/interfaces/HMI_API.xml
> +<function name="ButtonPress" functionID="ButtonPressID" messagetype="request">
@AKalinich-Luxoft `ButtonPress` already present in HMI_API and MOBILE_API updated according to the latest version
9402dc90b74d4c3d4932b95768ab1514f813f50d

2017-07-20 10:57 UTC, LitvinenkoIra commented
@LuxoftAKutsan @AByzhynar please review the latest changes

2017-07-20 11:00 UTC, AKalinich-Luxoft commented on src/components/can_cooperation/src/commands/button_press_request.cc
> +    LOG4CXX_WARN(logger_, "Request module type & data mismatch!");
@LitvinenkoIra can't see changes regarding this issue

2017-07-20 11:37 UTC, LuxoftAKutsan approved these changes

2017-07-20 13:25 UTC, AByzhynar requested changes

2017-07-20 13:25 UTC, AByzhynar commented on src/components/interfaces/MOBILE_API.xml
> +    <element name="ButtonPressID" value="100015" hexvalue="186B0" />
@LitvinenkoIra Looks that hex value must be `186AF`

2017-07-20 13:32 UTC, LitvinenkoIra commented on src/components/interfaces/MOBILE_API.xml
> +    <element name="ButtonPressID" value="100015" hexvalue="186B0" />
@AByzhynar Done 5237634901076c51319a3fc8ee5d9741d5a031ab

2017-07-20 13:33 UTC, AByzhynar approved these changes

2017-07-20 13:46 UTC, AKalinich-Luxoft approved these changes

2017-07-20 13:57 UTC, merged