Feature/implement ut for get interior vehicle data request
LuxoftAKutsan/sdl_core pull request #160
Opened 2017-07-22 11:03 UTC by AByzhynar

- Created base structure and mocks for RC command unit-tests
- Added constness to `Message` operator `==`
- Added UT for GetInteriorVehicleData class methods

2017-07-23 14:05 UTC, LuxoftAKutsan requested changes

2017-07-23 14:05 UTC, LuxoftAKutsan commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  void HandleMessage() {
@AByzhynar remove this function

2017-07-23 14:05 UTC, LuxoftAKutsan commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  can_cooperation::request_controller::MobileRequestPtr CreateCommand(
@AByzhynar Create funciton `CreateMessage` and make message as stack variable in test case

2017-07-23 14:05 UTC, LuxoftAKutsan commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, GetApplication(_)).WillOnce(Return(mock_app_));
@AByzhynar specify app_id for application

2017-07-23 14:05 UTC, LuxoftAKutsan commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, CheckPolicyPermissions(_))
@AByzhynar What argument retries CheckPolicyPermissions? ie is possible to verify it?

2017-07-23 14:05 UTC, LuxoftAKutsan commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_app_, AddExtension(_)).WillOnce(Return(true));
@AByzhynar check parameter

2017-07-23 14:05 UTC, LuxoftAKutsan commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  application_manager::AppExtensionPtr invalid_ext;
@AByzhynar please move all expectation after act

2017-07-24 09:32 UTC, LitvinenkoIra approved these changes

2017-07-24 11:34 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  can_cooperation::request_controller::MobileRequestPtr CreateCommand(
@LuxoftAKutsan Done in c8802d2fb6986392401620fd133bc367729e4470

2017-07-24 11:34 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  void HandleMessage() {
@LuxoftAKutsan Done in c8802d2fb6986392401620fd133bc367729e4470

2017-07-24 11:34 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, GetApplication(_)).WillOnce(Return(mock_app_));
@LuxoftAKutsan Done in c8802d2fb6986392401620fd133bc367729e4470

2017-07-24 11:34 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, CheckPolicyPermissions(_))
@LuxoftAKutsan Done in c8802d2fb6986392401620fd133bc367729e4470

2017-07-24 11:34 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  application_manager::AppExtensionPtr invalid_ext;
@LuxoftAKutsan Done in c8802d2fb6986392401620fd133bc367729e4470

2017-07-24 11:34 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/get_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_app_, AddExtension(_)).WillOnce(Return(true));
@LuxoftAKutsan Done in c8802d2fb6986392401620fd133bc367729e4470

2017-07-24 11:43 UTC, LuxoftAKutsan approved these changes

2017-07-24 13:19 UTC, merged