Remove module description from GetInteriorVehicleData processing
LuxoftAKutsan/sdl_core pull request #161
Opened 2017-07-23 13:08 UTC by LuxoftAKutsan

According to new API's
GetINteriorVehicleData transfer not moduleDescription structure but moduleTypes:

```xml
  <function name="GetInteriorVehicleData" functionID="GetInteriorVehicleDataID" messagetype="request">
    <param name="moduleType" type="ModuleType">
      <description>
        The type of a RC module to retrieve module data from the vehicle.
        In the future, this should be the Identification of a module.
      </description>
</param>
``` 

It required certain changes in Get/On interior data processing

2017-07-23 13:54 UTC, AByzhynar commented on src/components/can_cooperation/test/src/vehicle_data_subscription_test.cc
>  TEST(VehicleDataSubscription, CompareModuleDesciption) {
@LuxoftAKutsan Please remove module description from test case name

2017-07-23 13:54 UTC, AByzhynar approved these changes

2017-07-24 10:27 UTC, OlesiaV requested changes
```
<param name="isSubscribed" type="Boolean" mandatory="false" >
      <description>
       It is a conditional-mandatory parameter: must be returned in case "subscribe" parameter was present in the related request.
       if "true" - the "moduleType" from request is successfully subscribed and the head unit will send onInteriorVehicleData notifications for the moduleType.
       if "false" - the "moduleType" from request is either unsubscribed or failed to subscribe.
     </description>
   </param>
```
is missing in response in Mobile_API

2017-07-24 11:13 UTC, LuxoftAKutsan commented
@OlesiaV  please see https://github.com/LuxoftAKutsan/sdl_core/pull/161/commits/2a2ac3122347f32572f3135e53be8e7a831cdb83

2017-07-24 11:44 UTC, OlesiaV approved these changes

2017-07-24 11:50 UTC, merged