UT for OnInteriorVehicleData
LuxoftAKutsan/sdl_core pull request #171
Opened 2017-07-25 12:45 UTC by LitvinenkoIra

2017-07-25 15:23 UTC, AByzhynar requested changes

2017-07-25 15:23 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +const std::string json =
@LitvinenkoIra Variable named wrongly. Not according to project coding style

2017-07-25 15:23 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +  application_manager::MessagePtr result_msg;
@LitvinenkoIra 
Move it to the place before its first usage

2017-07-25 15:23 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +  EXPECT_CALL(*mock_service_, CheckPolicyPermissions(_))
@LitvinenkoIra Parameter verification?

2017-07-25 15:23 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +  EXPECT_CALL(*mock_service_, CheckModule(app_id_, "CLIMATE"))
@LitvinenkoIra Use constant instead of hardcoded value

2017-07-25 15:25 UTC, AByzhynar requested changes

2017-07-25 15:25 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +  const uint32_t app_id_ = 11u;
@LitvinenkoIra Why did you make it class member?

2017-07-25 15:25 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +TEST_F(OnInteriorVehicleDataNotificationTest, Execute_AppIsSubscribed) {
@LitvinenkoIra Test case name does not match its logic. Please rename.

2017-07-25 15:25 UTC, AByzhynar commented on src/components/can_cooperation/test/commands/on_interior_vehicle_data_notification_test.cc
> +TEST_F(OnInteriorVehicleDataNotificationTest, Execute_AppIsUnsubscribed) {
@LitvinenkoIra Test case name does not match its logic. Please rename.

2017-07-26 07:37 UTC, LuxoftAKutsan approved these changes

2017-07-26 07:38 UTC, AByzhynar approved these changes

2017-07-26 07:39 UTC, merged