UT for ButtonPress
LuxoftAKutsan/sdl_core pull request #175
Opened 2017-07-26 13:35 UTC by LitvinenkoIra

UT for ButtonPress

2017-07-26 13:55 UTC, LuxoftAKutsan requested changes

2017-07-26 13:55 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +  EXPECT_CALL(mock_module_, service()).WillOnce(Return(mock_service_));
@LitvinenkoIra redundant expect

2017-07-26 13:55 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +using namespace remote_control;
@LitvinenkoIra you are using a lot of from  remote_control and then use whole  remote_control namespace. Please avoid ```using namespace remote_control;```

2017-07-26 13:55 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +  const Json::Value hmi_request_params =
Json value may be const reference

2017-07-26 13:57 UTC, AByzhynar commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +  RemotePluginInterface::RCPluginEventDispatcher  event_dispatcher_;
@LitvinenkoIra Rdundant space

2017-07-26 14:02 UTC, AByzhynar requested changes

2017-07-26 14:02 UTC, AByzhynar commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +    message->set_function_name("ButtonPress");
@LitvinenkoIra Please use `GetMobileAPIName(MobileFunctionID func_id)` instead of hardcoding

2017-07-26 15:15 UTC, LitvinenkoIra commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +  EXPECT_CALL(mock_module_, service()).WillOnce(Return(mock_service_));
@LuxoftAKutsan Done fd882154f5c27e0df6d73766b839c25acbb9c21d

2017-07-26 15:15 UTC, LitvinenkoIra commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +using namespace remote_control;
@LuxoftAKutsan Done fd882154f5c27e0df6d73766b839c25acbb9c21d

2017-07-26 15:15 UTC, LitvinenkoIra commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +  const Json::Value hmi_request_params =
@LuxoftAKutsan Done fd882154f5c27e0df6d73766b839c25acbb9c21d

2017-07-26 15:15 UTC, LitvinenkoIra commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +  RemotePluginInterface::RCPluginEventDispatcher  event_dispatcher_;
@AByzhynar Done
fd882154f5c27e0df6d73766b839c25acbb9c21d

2017-07-26 15:15 UTC, LitvinenkoIra commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +    message->set_function_name("ButtonPress");
@AByzhynar Done
fd882154f5c27e0df6d73766b839c25acbb9c21d

2017-07-27 11:09 UTC, AByzhynar commented on src/components/remote_control/test/commands/button_press_request_test.cc
> +    Execute_ButtonNameDoesNotMatchModuleType_ExpectMessageNotSentToHMI_AndFalseSentToMobile) {
@LitvinenkoIra :+1:

2017-07-27 11:26 UTC, LuxoftAKutsan approved these changes

2017-07-27 11:34 UTC, AByzhynar approved these changes

2017-07-27 12:37 UTC, merged