Fix SDL doesn't transfer info parameter received from HMI
LuxoftAKutsan/sdl_core pull request #177
Opened 2017-07-26 14:33 UTC by LitvinenkoIra

Fix SDL doesn't transfer "info" parameter received from HMI in case of erroneous response

2017-07-26 14:34 UTC, AByzhynar approved these changes

2017-07-26 14:58 UTC, LuxoftAKutsan approved these changes

2017-07-27 07:19 UTC, AByzhynar commented
@LitvinenkoIra Fix Unit tests according to your changes in code

2017-07-27 07:19 UTC, AByzhynar requested changes

2017-07-27 07:19 UTC, AByzhynar commented on src/components/remote_control/src/commands/get_interior_vehicle_data_request.cc
> -    info = "Invalid message received from vehicle";
@LitvinenkoIra Fix Unit tests according to your changes in code

2017-07-27 11:10 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/get_interior_vehicle_data_request.cc
> -    info = "Invalid message received from vehicle";
@AByzhynar Done b40bce1d6f18e5e182d7f77868d13f832c921ef2

2017-07-27 14:27 UTC, AByzhynar approved these changes

2017-07-27 14:37 UTC, merged