Resource allocation
LuxoftAKutsan/sdl_core pull request #179
Opened 2017-07-27 14:09 UTC by LuxoftAKutsan

Partial implementation of resource allocation module

2017-07-27 14:17 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +  virtual AquireResult::eType AquireResource(const std::string& module_type,
Acquire 
fix it everywhere

2017-07-27 14:34 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/remote_control_plugin.h
> +  ResourceAlocationManagerImpl resource_alocation_manager_;
@LuxoftAKutsan A*ll*ocation

2017-07-27 14:59 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief AskDriver send OnInteriorConcent request to HMI for aqquiring
@LuxoftAKutsan consent

2017-07-27 14:59 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief AskDriver send OnInteriorConcent request to HMI for aqquiring
@LuxoftAKutsan acquiring

2017-07-27 15:43 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +                  "Resource is not ys aquired. "
@LuxoftAKutsan `ys` ?

2017-07-27 15:52 UTC, AByzhynar requested changes

2017-07-27 15:52 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  if (AccessMode::AUTO_DENY == current_access_mode_) {
@LuxoftAKutsan May be move this check up?

2017-07-27 15:52 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +                  "Aquiring resources now alllowed in "
@LuxoftAKutsan typo

2017-07-27 15:52 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  if (AccessMode::AUTO_ALLOW == current_access_mode_) {
@LuxoftAKutsan We can use switch instead of ifs

2017-07-28 09:18 UTC, LuxoftAKutsan commented on src/components/remote_control/include/remote_control/remote_control_plugin.h
> +  ResourceAlocationManagerImpl resource_alocation_manager_;
fixed

2017-07-28 09:18 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  if (AccessMode::AUTO_DENY == current_access_mode_) {
@AByzhynar if policy id AUTODENY but resource is not acquired , SDL should allow acquire this resource

2017-07-28 09:18 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  if (AccessMode::AUTO_ALLOW == current_access_mode_) {
fixed

2017-07-28 09:26 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief OnDriverDisallowed callback for rejecting aquiring resource
acquiring

2017-07-28 09:26 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief AskDriver send OnInteriorConcent request to HMI for aqquiring
acquiring

2017-07-28 09:30 UTC, LitvinenkoIra commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  const application_manager::ApplicationSharedPtr aquiring_app =
acquiring_app

2017-07-28 09:31 UTC, LitvinenkoIra commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  const mobile_apis::HMILevel::eType aquiring_app_hmi_level =
acquiring_app_hmi_level

2017-07-28 09:33 UTC, LitvinenkoIra commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  LOG4CXX_DEBUG(logger_, "Force " << app_id << " aquiring " << module_type);
acquiring

2017-07-28 10:08 UTC, AByzhynar requested changes

2017-07-28 10:08 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   *         ASK_DRIVER is driver confirm is required
@LuxoftAKutsan confirm -> confirmation or approval

2017-07-28 10:15 UTC, AByzhynar requested changes

2017-07-28 10:15 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager_impl.h
> +  ~ResourceAllocationManagerImpl() OVERRIDE FINAL;
@LuxoftAKutsan `FINAL` && `OVERRIDE` are redundant for `dtor`

2017-07-28 10:15 UTC, AByzhynar commented on src/components/remote_control/src/commands/base_command_request.cc
> +struct OnDrivesAnswerImpl : AskDriverCallBack {
@LuxoftAKutsan OnDrives???

2017-07-28 10:17 UTC, AByzhynar requested changes

2017-07-28 10:17 UTC, AByzhynar commented on src/components/remote_control/src/commands/base_command_request.cc
> +    bool allowed = value[message_params::kAllowed].asBool();
@LuxoftAKutsan const?

2017-07-28 10:19 UTC, AByzhynar requested changes

2017-07-28 10:19 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/set_interior_vehicle_data_request.h
> +  AcquireResult::eType AcquireResource(
@LuxoftAKutsan Add description please

2017-07-28 10:25 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +                    "Driver confirm required for allowing "
@LuxoftAKutsan Driver confirm required for allowing " - > Driver confirmation required to allow "

2017-07-28 10:25 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +                        << app_id << " aquiring " << module_type);
@LuxoftAKutsan to acquire

2017-07-28 10:49 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +   * In case if allocation of resource is not required, return ALLOWD by
ALLOWED

2017-07-28 10:52 UTC, LitvinenkoIra approved these changes

2017-07-28 11:55 UTC, AByzhynar requested changes

2017-07-28 11:55 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/remote_plugin_interface.h
> +  virtual ResourceAllocationManager& resource_allocator_manager() = 0;
@LuxoftAKutsan resource_allocator_manager()-> resource_allocation_manager()

2017-07-28 11:56 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> + * @brief The AskDriverCallBack class callback for GetInteriourConcent response
@LuxoftAKutsan concent ->consent

2017-07-28 11:56 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief AcquireResource acquires resource by applicaion
@LuxoftAKutsan application

2017-07-28 11:57 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @param app_id applicaiton that acquire resource
@LuxoftAKutsan application insted of applicaion

2017-07-28 11:57 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief AcquireResource forses acquiring resource by applicaion
@LuxoftAKutsan application insted of applicaion

2017-07-28 11:57 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @brief AcquireResource forses acquiring resource by applicaion
@LuxoftAKutsan forCes

2017-07-28 11:57 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @param app_id applicaiton that acquire resource
@LuxoftAKutsan application insted of applicaion

2017-07-28 11:59 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +   * @param callback will be executed on OnInteriorConcent response
@LuxoftAKutsan conSent

2017-07-28 13:18 UTC, AByzhynar approved these changes

2017-07-29 16:08 UTC, merged