Feature/implement get interior vehicle data consent rpc
LuxoftAKutsan/sdl_core pull request #182
Opened 2017-07-29 16:06 UTC by AByzhynar

Implemented GetInteriorVehicleDataConsent RPC and its integration
with resource allocation manager

2017-07-30 09:30 UTC, LuxoftAKutsan requested changes

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  LOG4CXX_DEBUG(logger_, "\nRequest to HMI: \n" << json_msg);
@AByzhynar why do you need in log \n? Remove it

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  std::vector<std::string> list_of_rejected_resources =
@AByzhynar const ref

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
>                                                AskDriverCallBackPtr callback) {
@AByzhynar I would DCHECK or return callback pointer

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  application_manager::MessagePtr message_to_send(
@AByzhynar why not wake shared ?

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  params[json_keys::kAppId] = hmi_app_id;
@AByzhynar I would extract part of this code to Remote MessageHelper

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +      rejected_resources_for_application_[app_id];
@AByzhynar in that case *it would be better

2017-07-30 09:30 UTC, LuxoftAKutsan commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  RejectedResources::iterator it =
@AByzhynar I would name it rejected_resources_list_it;
And the last line would be 
```
 return helpers::in_range(*rejected_resources_list_it, module_type);
```

2017-07-30 09:42 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  RejectedResources::iterator it =
@LuxoftAKutsan First parameter of `in_range` is container. Not `pair` . 
- First - I consider that this way is more readable 
- Second - I don't want to use *rejected_resources_list_it->second

2017-07-30 09:44 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  params[json_keys::kAppId] = hmi_app_id;
@LuxoftAKutsan I thought about it but could see no sense as this message as created & used only here. Thus I decided to leave it here on stack.

2017-07-30 09:45 UTC, AByzhynar commented
Rebuild required

2017-07-31 07:42 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +                  "Driver disallowed app:" << app_id << " to acquirie "
@AByzhynar please add space after `app:` and typo in `acquirie`

2017-07-31 09:52 UTC, LitvinenkoIra approved these changes

2017-07-31 10:53 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
>                                                AskDriverCallBackPtr callback) {
@LuxoftAKutsan Done in f00751f7acffdabcddd4bac8580f6777d91a3205

2017-07-31 10:53 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  application_manager::MessagePtr message_to_send(
@LuxoftAKutsan Done in f00751f7acffdabcddd4bac8580f6777d91a3205

2017-07-31 10:53 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  std::vector<std::string> list_of_rejected_resources =
@LuxoftAKutsan Done in f00751f7acffdabcddd4bac8580f6777d91a3205

2017-07-31 10:54 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +                  "Driver disallowed app:" << app_id << " to acquirie "
@AKalinich-Luxoft Done in f00751f7acffdabcddd4bac8580f6777d91a3205

2017-07-31 10:59 UTC, AKalinich-Luxoft approved these changes

2017-07-31 16:51 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  params[json_keys::kAppId] = hmi_app_id;
@LuxoftAKutsan Done in f6468943649ab13c7c8fd0944a440606fc1ff055

2017-08-01 06:04 UTC, AByzhynar commented
@LuxoftAKutsan please finish your review

2017-08-01 06:56 UTC, LuxoftAKutsan approved these changes

2017-08-01 07:23 UTC, merged