Feature/on remote control settings
LuxoftAKutsan/sdl_core pull request #183
Opened 2017-07-31 17:49 UTC by LitvinenkoIra

2017-08-01 07:19 UTC, AKalinich-Luxoft requested changes
Also please don't forget to rebase on baseline because your pull request contains commits from another pull request

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> + Copyright (c) 2013, Ford Motor Company
@LitvinenkoIra 2017

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +  bool Validate() OVERRIDE {
@LitvinenkoIra propose to move this function implementation to `BaseCommandNotification` where it is pure virtual and make this a behaviour by default. Then you could remove this code from `OnRemoteControlSettingsNotification` and from `OnInteriorVehicleDataNotification`

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +OnRemoteControlSettingsNotification::~OnRemoteControlSettingsNotification() {}
@LitvinenkoIra I think dtor by default could be used here, so this empty declaration seems redundant

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  const Json::Value radio = MessageHelper::StringToValue(enums_value::kRadio);
@LitvinenkoIra always try to declare variables before place of their first use. As near as it possible.
Suggest to move declaration of `radio` variable after first `if` block.

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  LOG4CXX_DEBUG(logger_, "Not allowed");
@LitvinenkoIra probably better to replace with `LOG4CXX_AUTO_TRACE`

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +        rc_module_.resource_allocator_manager();
@LitvinenkoIra propose to rename to `resource_allocation_manager()`

2017-08-01 07:19 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  else {
@LitvinenkoIra redundant empty line before else

2017-08-01 07:22 UTC, AByzhynar commented
Rebuild required

2017-08-01 10:33 UTC, LitvinenkoIra commented
Rebuild required

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> + Copyright (c) 2013, Ford Motor Company
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +  bool Validate() OVERRIDE {
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +OnRemoteControlSettingsNotification::~OnRemoteControlSettingsNotification() {}
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  const Json::Value radio = MessageHelper::StringToValue(enums_value::kRadio);
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  LOG4CXX_DEBUG(logger_, "Not allowed");
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +        rc_module_.resource_allocator_manager();
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 10:59 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  else {
@AKalinich-Luxoft Done 70659492cbf219ff6bbaab6343b17d113e73c914

2017-08-01 11:03 UTC, AKalinich-Luxoft approved these changes

2017-08-01 13:56 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +      RemotePluginInterface& rc_module);
@LitvinenkoIra Missed description

2017-08-01 13:57 UTC, AByzhynar requested changes

2017-08-01 13:57 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +  void ProcessRCNotAllowed();
@LitvinenkoIra Missed description

2017-08-01 13:59 UTC, LuxoftAKutsan approved these changes

2017-08-01 13:59 UTC, LuxoftAKutsan commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +CREATE_LOGGERPTR_GLOBAL(logger_, "OnRemoteControlSettingsNotification");
@LitvinenkoIra use global remote controller logger name

2017-08-01 14:09 UTC, AByzhynar requested changes

2017-08-01 14:09 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager_impl.h
> +      const hmi_apis::Common_RCAccessMode::eType access_mode) OVERRIDE FINAL;
@LitvinenkoIra In this case FINAL includes OVERRIDE - Thus OVERRIDE can be safely removed

2017-08-01 14:12 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +CREATE_LOGGERPTR_GLOBAL(logger_, "OnRemoteControlSettingsNotification");
@LuxoftAKutsan No!

2017-08-01 14:16 UTC, AByzhynar commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +    RemotePluginInterface& rc_module)
@LitvinenkoIra May be const?

2017-08-01 14:49 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/resource_allocation_manager_impl.h
> +      const hmi_apis::Common_RCAccessMode::eType access_mode) OVERRIDE FINAL;
@AByzhynar please see the latest updates ed6379f1300d0f2493206a1ed7e0f581e8cc764a

2017-08-01 14:49 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +  void ProcessRCNotAllowed();
@AByzhynar Change function name and add description ed6379f1300d0f2493206a1ed7e0f581e8cc764a

2017-08-01 14:50 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +      RemotePluginInterface& rc_module);
@AByzhynar ed6379f1300d0f2493206a1ed7e0f581e8cc764a

2017-08-01 14:57 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> +   */
@LitvinenkoIra 
```
Disalows RC functionality for all RC apps
- All registered apps will be put to NONE hmi level
- All registered apps will be unsubsribed...
```

2017-08-01 15:10 UTC, AByzhynar approved these changes

2017-08-01 15:21 UTC, dev-gh requested changes

2017-08-01 15:21 UTC, dev-gh commented on src/components/functional_module/include/functional_module/function_ids.h
> +  ON_REMOTE_CONTROL_SETTINGS,
@LitvinenkoIra 
I think it must have ID matching to the same in API

2017-08-01 15:21 UTC, dev-gh commented on src/components/functional_module/include/functional_module/generic_module.h
> +  std::deque<RCFunctionID> mobile_function_list;
@LitvinenkoIra 
If you renamed enum you have to rename this member to keep consistency

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/base_command_notification.h
> +  virtual bool Validate();
@LitvinenkoIra 
Why no description?

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> + protected:
@LitvinenkoIra 
Why not private?

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +  virtual void SetAccessMode(
@LitvinenkoIra 
Description is missing

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  if (extension->IsSubscibedToInteriorVehicleData(climate)) {
@LitvinenkoIra 
I think there is no sense to check before unsubsription

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  typedef std::vector<application_manager::ApplicationSharedPtr> AppPtrs;
@LitvinenkoIra 
I would suggest not to mention whether hidden implementation is pointer or some other type as if you'll change that later typedef name can be confusing

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +    hmi_apis::Common_RCAccessMode::eType access_mode_ =
@LitvinenkoIra 
const

2017-08-01 15:21 UTC, dev-gh commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +    RCAppExtensionPtr extension =
@LitvinenkoIra 
const

2017-08-01 15:43 UTC, LitvinenkoIra commented on src/components/functional_module/include/functional_module/function_ids.h
> +  ON_REMOTE_CONTROL_SETTINGS,
@dev-gh but we don't have ID for this notification in API

2017-08-01 16:09 UTC, LitvinenkoIra commented on src/components/functional_module/include/functional_module/generic_module.h
> +  std::deque<RCFunctionID> mobile_function_list;
@dev-gh Done de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:09 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/base_command_notification.h
> +  virtual bool Validate();
@dev-gh Added description de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:10 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/commands/on_remote_control_settings_notification.h
> + protected:
@dev-gh changed to private de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:10 UTC, LitvinenkoIra commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +  virtual void SetAccessMode(
@dev-gh Added description de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:10 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  if (extension->IsSubscibedToInteriorVehicleData(climate)) {
@dev-gh Done de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:10 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +  typedef std::vector<application_manager::ApplicationSharedPtr> AppPtrs;
@dev-gh Done de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:11 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +    RCAppExtensionPtr extension =
@dev-gh Done de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-01 16:11 UTC, LitvinenkoIra commented on src/components/remote_control/src/commands/on_remote_control_settings_notification.cc
> +    hmi_apis::Common_RCAccessMode::eType access_mode_ =
@dev-gh Done de7c8a44d913fde5bcb8d38a4f21ba18fdcc1275

2017-08-02 11:27 UTC, dev-gh approved these changes

2017-08-02 11:59 UTC, merged