Unit tests for SetInteriorVehicleData
LuxoftAKutsan/sdl_core pull request #187
Opened 2017-08-02 14:31 UTC by Itileda

@LuxoftAKutsan, @AKalinich-Luxoft, @AByzhynar, @LitvinenkoIra 
Please, review the pull request with unit tests for SetInteriorVehicleData

2017-08-03 07:00 UTC, LuxoftAKutsan requested changes

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +      SIVD_HMI_Response;
@Itileda response and event are different entities. Please do not mix this names. use event in typedef

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +    mock_module_.set_service(exp_service);
@Itileda setting anything to mock is redundant

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  const uint32_t app_id_ = 11u;
@Itileda please name constant according kostant name convention: kAppId
https://google.github.io/styleguide/cppguide.html

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(mock_module_, service())
@Itileda you already created ON_CALL for service getter. expect is redundant. Also please avoid using oncalls for getters and not logical critical blocks.

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, GetApplication(mobile_message->connection_key()))
@Itileda you already created ON_CALL for service getter. expect is redundant.

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_app_, AddExtension(_))
@Itileda this part of unit test is the crux part of UT. please emphasize it with spaces

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(mock_module_, service())
@Itileda you already created ON_CALL for service getter. expect is redundant.  ( same as in prev UT)

2017-08-03 07:00 UTC, LuxoftAKutsan commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(mock_module_, service()).WillOnce(Return(mock_service_));
@Itileda you already created ON_CALL for service getter. expect is redundant. ( same as in prev UT)

2017-08-03 07:05 UTC, AKalinich-Luxoft requested changes

2017-08-03 07:05 UTC, AKalinich-Luxoft commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +      SIVD_HMI_Response;
@Itileda please be consistent when define new type names. For example remove underscopes in this type name - `SivdHmiResponse`

2017-08-03 07:05 UTC, AKalinich-Luxoft commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +        .WillRepeatedly(ReturnRef(event_dispatcher_));
@Itileda probably `ON_CALL` here would be better

2017-08-03 07:05 UTC, AKalinich-Luxoft commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  const uint32_t app_id_ = 11u;
@Itileda propose to move this const to namespace with other constants at line 70

2017-08-03 07:05 UTC, AKalinich-Luxoft commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, GetNextCorrelationID()).WillOnce(Return(1));
@Itileda propose to create const variable `const uint32_t kCorrelationId = 1u` and use it instead of direct values. Check all places where correlation id used.

2017-08-03 07:05 UTC, AKalinich-Luxoft commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +       Execute_ValidMessageWithoutSettableAndWithReadOnlyParams) {
@Itileda please add expectation result after scenario in UT name for all UT's

2017-08-03 13:00 UTC, AByzhynar requested changes

2017-08-03 13:00 UTC, AByzhynar commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +    message->set_function_name("SetInteriorVehicleData");
@Itileda Use GetMobileAPIName() function instead of hardcoding

2017-08-03 13:00 UTC, AByzhynar commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  const uint32_t app_id_ = 11u;
@Itileda why do you need it as class member?

2017-08-03 13:24 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +      SIVD_HMI_Response;
Accepted.
Fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4 by removing ,was not used at all

2017-08-03 13:25 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +    mock_module_.set_service(exp_service);
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:25 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  const uint32_t app_id_ = 11u;
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:25 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(mock_module_, service())
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:26 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, GetApplication(mobile_message->connection_key()))
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:26 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_app_, AddExtension(_))
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:27 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(mock_module_, service())
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:27 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(mock_module_, service()).WillOnce(Return(mock_service_));
@LuxoftAKutsan - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:32 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +      SIVD_HMI_Response;
@AKalinich-Luxoft - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:33 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +        .WillRepeatedly(ReturnRef(event_dispatcher_));
@AKalinich-Luxoft - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:33 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  const uint32_t app_id_ = 11u;
@AKalinich-Luxoft - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:33 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  EXPECT_CALL(*mock_service_, GetNextCorrelationID()).WillOnce(Return(1));
@AKalinich-Luxoft - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:34 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +       Execute_ValidMessageWithoutSettableAndWithReadOnlyParams) {
@AKalinich-Luxoft - accepted, fixed in fd690ae270ce87c485c1dd8ce1f7574e101e98b4

2017-08-03 13:35 UTC, AKalinich-Luxoft approved these changes

2017-08-03 13:59 UTC, LitvinenkoIra approved these changes

2017-08-03 14:00 UTC, LitvinenkoIra commented
@Itileda Fix code style please

2017-08-03 14:26 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +    message->set_function_name("SetInteriorVehicleData");
@AByzhynar, accepted - fixed in ea4a85f19c816df9c18c89177cff80e6dd121392.

2017-08-03 14:26 UTC, Itileda commented on src/components/remote_control/test/commands/set_interior_vehicle_data_request_test.cc
> +  const uint32_t app_id_ = 11u;
@AByzhynar, accepted - fixed in ea4a85f19c816df9c18c89177cff80e6dd121392, moved to namespace.

2017-08-03 16:42 UTC, AByzhynar approved these changes

2017-08-04 08:33 UTC, LuxoftAKutsan approved these changes

2017-08-04 09:18 UTC, Itileda commented
Rebuild required

2017-08-04 10:18 UTC, merged