Fixes simultaneous processing of RC RPCs
LuxoftAKutsan/sdl_core pull request #191
Opened 2017-08-03 16:00 UTC by dev-gh

In case some RC request is pending and uses allocated resource (module)
another request must consider such resource as having 'busy' state and
do not try to re-acquire it. SDL must return 'in use' result in that
case.

2017-08-03 16:14 UTC, AByzhynar requested changes

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/button_press_request.h
> +  bool IsResourceFree(const std::string& module_type) const OVERRIDE FINAL;
@dev-gh OVERRIDE is redundant is this case.

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/button_press_request.h
> +                        const ResourceState::eType state) OVERRIDE FINAL;
@dev-gh OVERRIDE is redundant is this case.

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/set_interior_vehicle_data_request.h
> +  bool IsResourceFree(const std::string& module_type) const OVERRIDE FINAL;
@dev-gh OVERRIDE is redundant is this case.

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/commands/set_interior_vehicle_data_request.h
> +                        const ResourceState::eType state) OVERRIDE FINAL;
@dev-gh OVERRIDE is redundant is this case.

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +enum eType { AUTO_ALLOW = 0, AUTO_DENY, ASK_DRIVER };
@dev-gh This enum is redundant. Use please from hmi_api

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/include/remote_control/resource_allocation_manager_impl.h
> +                        const ResourceState::eType state) OVERRIDE FINAL;
@dev-gh OVERRIDE is redundant is this case.

2017-08-03 16:14 UTC, AByzhynar commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +
@dev-gh 
Redundant empty line

2017-08-04 07:26 UTC, AKalinich-Luxoft requested changes

2017-08-04 07:26 UTC, AKalinich-Luxoft commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +   * need to manager the resources
@dev-gh "to manage the resources"

2017-08-04 07:26 UTC, AKalinich-Luxoft commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +   * need to manager the resources
@dev-gh same as above

2017-08-04 07:26 UTC, AKalinich-Luxoft commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +    UNUSED(state);
@dev-gh probably you should also specify explicitly that first parameter is unused too or not specify that at all. Also please add description of the first param

2017-08-04 07:26 UTC, AKalinich-Luxoft commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  LOG4CXX_DEBUG(logger_, "Resource " << module_type << " is acquired.");
@dev-gh maybe to concatenate this log messages into one message, separated with '.' ?

2017-08-04 08:24 UTC, LuxoftAKutsan approved these changes

2017-08-04 08:32 UTC, LitvinenkoIra approved these changes

2017-08-04 09:03 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/button_press_request.h
> +  bool IsResourceFree(const std::string& module_type) const OVERRIDE FINAL;
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:03 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/button_press_request.h
> +                        const ResourceState::eType state) OVERRIDE FINAL;
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:03 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/set_interior_vehicle_data_request.h
> +  bool IsResourceFree(const std::string& module_type) const OVERRIDE FINAL;
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:03 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/set_interior_vehicle_data_request.h
> +                        const ResourceState::eType state) OVERRIDE FINAL;
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/include/remote_control/resource_allocation_manager.h
> +enum eType { AUTO_ALLOW = 0, AUTO_DENY, ASK_DRIVER };
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/include/remote_control/resource_allocation_manager_impl.h
> +                        const ResourceState::eType state) OVERRIDE FINAL;
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +
@AByzhynar 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +   * need to manager the resources
@AKalinich-Luxoft 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +   * need to manager the resources
@AKalinich-Luxoft 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/include/remote_control/commands/base_command_request.h
> +    UNUSED(state);
@AKalinich-Luxoft 
Done with 8e6cec8

2017-08-04 09:04 UTC, dev-gh commented on src/components/remote_control/src/resource_allocation_manager_impl.cc
> +  LOG4CXX_DEBUG(logger_, "Resource " << module_type << " is acquired.");
@AKalinich-Luxoft 
Done with 8e6cec8

2017-08-04 09:29 UTC, AKalinich-Luxoft approved these changes

2017-08-04 11:00 UTC, AByzhynar approved these changes

2017-08-04 11:00 UTC, AByzhynar commented
@dev-gh Please check Build failure. Some UT failed.

2017-08-04 12:11 UTC, LitvinenkoIra commented
Rebuild required

2017-08-04 12:34 UTC, dev-gh commented
@AByzhynar 
Done with 5c375b3

2017-08-04 13:14 UTC, AByzhynar commented
@dev-gh Please check Build failure. Some UT failed.

2017-08-04 17:15 UTC, merged