Integrate system capabilities
LuxoftAKutsan/sdl_core pull request #196
Opened 2017-08-06 14:33 UTC by LuxoftAKutsan

2017-08-07 06:24 UTC, LuxoftAKutsan commented
Rebuild required

2017-08-07 06:25 UTC, LuxoftAKutsan commented
@dev-gh @AKalinockLuxoft please review

2017-08-07 09:02 UTC, AKalinich-Luxoft requested changes

2017-08-07 09:02 UTC, AKalinich-Luxoft commented on src/components/application_manager/src/commands/hmi/rc_get_capabilities_response.cc
> +  HMICapabilities& hmi_capabilities = application_manager_.hmi_capabilities();
@LuxoftAKutsan this line also could be moved inside if at line 50

2017-08-07 09:02 UTC, AKalinich-Luxoft commented on src/components/application_manager/src/commands/mobile/get_system_capability_request.cc
> +  // response_params[strings::system_capability][strings::system_capability_type]
@LuxoftAKutsan please remove this comment

2017-08-07 09:02 UTC, AKalinich-Luxoft commented on src/components/application_manager/src/commands/mobile/get_system_capability_request.cc
> +  mobile_apis::SystemCapabilityType::eType response_type =
@LuxoftAKutsan can be const

2017-08-07 09:02 UTC, AKalinich-Luxoft commented on src/components/application_manager/test/commands/hmi/rc_is_ready_request_test.cc
> +                         am::HmiInterfaces::InterfaceState state) {
@LuxoftAKutsan all params could be const

2017-08-07 09:02 UTC, AKalinich-Luxoft commented on src/components/remote_control/include/remote_control/rc_module_constants.h
> +const char kbuttonCapabilities[] = "buttonCapabilities";
@LuxoftAKutsan please use upper case character after 'k' symbol

2017-08-09 07:06 UTC, AKalinich-Luxoft approved these changes

2017-08-09 11:51 UTC, LitvinenkoIra approved these changes

2017-08-09 11:51 UTC, LitvinenkoIra commented on src/components/application_manager/src/commands/hmi/rc_is_ready_request.cc
> +  // Note(dtrunov): According to new requirment APPLINK-27956
@LuxoftAKutsan remove this comment pls

2017-08-09 17:20 UTC, merged